language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
notifications:
  email:
    recipients:
    - my.gama.bot@gmail.com
    on_success: change
    on_failure: always
cache:
  directories:
  - "$HOME/.m2"
after_success: sh ./github-release.sh "gama-platform/gama" "latest" $HOME/.m2/repository/msi/gama/msi.gama.application.product/1.7.0-SNAPSHOT/*