language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
notifications:
  email:
    recipients:
    - my.gama.bot@gmail.com
    on_success: never
    on_failure: never
cache:
  directories:
  - "$HOME/.m2"
script: sh ./build.sh
after_success: sh ./github-release.sh
branches:
  only:
    - travis-test
